### PR TITLE
Added new mouse layout to support mouse Button4 & Button5

### PR DESCRIPTION
**Pull request by nrpieper**
Added new mouse layout: 'Layout_Buttons1-5_Forward+Back', for a standard 5 button mouse, adding Button4 & Button5

### CODE REVIEW

**Comment by 1onar** [comment]
Thank you for your pull request; however, it’s not necessary as you can customize your own mouse layout.

Please refer to the instruction video for detailed guidance:
[https://youtu.be/ClGztJtR2rQ?si=5fMRxXHRkDIzGMA0](https://youtu.be/ClGztJtR2rQ?si=5fMRxXHRkDIzGMA0)

**Comment by nrpieper** [comment]
The mouse layout customization video doesn't show how to add mouse button 4 and 5 to a layout and none of the built-in layouts included these buttons. Am I missing something?

**Comment by 1onar** [comment]
If the keys are "unlocked" you can hover above them and click the wanted keybind. The text changes but the icon does only change when you save it.

https://youtu.be/ClGztJtR2rQ/&t=0m24s

**Comment by nrpieper** [comment]
Got it figured out.  Thanks

**Pull request closed without merging**
